# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a82e5a25e990175ba1e06e700c2ba19440b5f430800c2a6c4cc644c83901d140b3c6eef8d75d6837beb0019d6ebce03ac528293f66895e3c5b4dee8afc3f02b6

test:
  secret_key_base: f761a7ae68727e9cd7f007b1b3f4648bc9142dd128acad18ba59471ce7b93952224bedd0233f1e07535edee37cebcb6403748243b9d6a7863b1f32bc61d2a419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
